version: "3.4"

services:
  syslog-web:
    image: pysyslog-web-nginx:latest
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: psysylog-web
    ports:
      - 80:80
    volumes:
      - ./frontend/env/:/var/www/html/env/ # environment variables to be put into the browser such as the API URL
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - frontnet
      - backnet

  syslog-web-api:
    image: pysyslog-web-api:latest
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: pysyslog-web-api
    ports:
      - 3000:3000
    environment:
      - MONGODB_URI=mongodb://mongoadmin:m0ngoadminPW!@mongo # username/password should be same as below
      - SYSLOG_SERVER_ADDR=pysyslog-server
    networks:
      - backnet

  syslog-server:
    image: willchamness/pysyslog-server:latest
    container_name: pysyslog-server
    ports:
      - 514:514/udp
    environment:
      - SYSLOG_FILE=syslog.log
      - SYSLOG_LISTEN_ADDRESS=0.0.0.0
      - SYSLOG_LISTEN_PORT=514
      - SYSLOG_USE_DB=yes # if set to 'no', ignore mongodb configuration
      - MONGODB_URI=mongodb://mongoadmin:m0ngoadminPW!@mongo # username/password should be same as below
      - MONGODB_DBNAME=syslog
      - MONGODB_COLLECTION=logs
      - TZ=America/New_York
    volumes:
      - ./syslog:/app/syslog
    networks:
      - frontnet
      - backnet

  mongo:
    image: mongo:4.4
    container_name: pysyslog-db
    ports:
      - 27017:27017
    logging:
      options:
        max-size: 1g
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=m0ngoadminPW!
    volumes:
      - ./mongodb-data:/data/db
    networks:
      - backnet

networks:
  frontnet:
    name: pysyslog_frontnet
  backnet:
    internal: true
    name: pysyslog_backnet
